######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 26 11:13:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 
INCLUDEPATH += . /usr/include/poppler/qt4
LIBS += -L/usr/lib -lpoppler-qt4

# Input
HEADERS += PDFFactory.h PDFFile.h PDFPageWidget.h
SOURCES += main.cpp PDFFactory.cpp PDFFile.cpp PDFPageWidget.cpp
RESOURCES += pdffactory.qrc
