######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 5 21:41:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PDFFactory.h
SOURCES += main.cpp PDFFactory.cpp
RESOURCES += pdffactory.qrc

CONFIG += console
